import { Event } from './types';

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Neon Nights: Cyberpunk Rave',
    description: 'Immerse yourself in a futuristic soundscape with top DJs and stunning light shows. Experience the energy of the future today.',
    date: '2026-04-15',
    time: '22:00',
    location: 'Area 51 Warehouse, Brooklyn',
    image: 'https://images.unsplash.com/photo-1574391884720-385e6e288793?q=80&w=2070&auto=format&fit=crop',
    category: 'Music',
    capacity: 2000,
    ticketsSold: 1240,
    price: 45,
    organizer: 'Future Sounds',
    organizerId: 'org1',
  },
  {
    id: '2',
    title: 'Tech Summit 2026',
    description: 'The premier conference for innovation, featuring keynote speakers from top tech giants. Network with industry leaders and discover the latest trends.',
    date: '2026-05-20',
    time: '09:00',
    location: 'Javits Center, NYC',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2070&auto=format&fit=crop',
    category: 'Technology',
    capacity: 5000,
    ticketsSold: 4500,
    price: 299,
    organizer: 'TechWorld Inc.',
    organizerId: 'org2',
  },
  {
    id: '3',
    title: 'Shakespeare in the Park: Hamlet',
    description: 'A modern retelling of the classic tragedy under the stars. Enjoy a night of culture and emotion in the beautiful Central Park.',
    date: '2026-06-10',
    time: '19:30',
    location: 'Central Park Delacorte Theater',
    image: 'https://images.unsplash.com/photo-1503095392237-fa31294879b6?q=80&w=2070&auto=format&fit=crop',
    category: 'Arts',
    capacity: 1500,
    ticketsSold: 1500, // Sold out
    price: 0,
    organizer: 'Public Theater',
    organizerId: 'org3',
  },
  {
    id: '4',
    title: 'Global Food Festival',
    description: 'Taste dishes from over 50 countries prepared by master chefs. A culinary journey you won\'t forget.',
    date: '2026-04-25',
    time: '11:00',
    location: 'Prospect Park, Brooklyn',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=1974&auto=format&fit=crop',
    category: 'Activities',
    capacity: 10000,
    ticketsSold: 3200,
    price: 15,
    organizer: 'Foodies Unite',
    organizerId: 'org4',
  },
  {
    id: '5',
    title: 'Championship Finals: NYC vs LA',
    description: 'Witness the clash of titans in the season finale. The energy, the rivalry, the game of the year.',
    date: '2026-05-30',
    time: '20:00',
    location: 'Madison Square Garden',
    image: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?q=80&w=2069&auto=format&fit=crop',
    category: 'Sports',
    capacity: 20000,
    ticketsSold: 19500,
    price: 150,
    organizer: 'National League',
    organizerId: 'org5',
  },
  {
    id: '6',
    title: 'Modern Art Gallery Opening',
    description: 'Exclusive preview of the new avant-garde collection. Champagne and hors d\'oeuvres will be served.',
    date: '2026-04-18',
    time: '18:00',
    location: 'SoHo Gallery',
    image: 'https://images.unsplash.com/photo-1518998053901-5348d3969105?q=80&w=1974&auto=format&fit=crop',
    category: 'Arts',
    capacity: 200,
    ticketsSold: 150,
    price: 75,
    organizer: 'Art Collective',
    organizerId: 'org6',
  },
  {
    id: '7',
    title: 'Stand-up Comedy Night',
    description: 'Laugh your heart out with the funniest comedians in the city. A night of pure joy and entertainment.',
    date: '2026-04-22',
    time: '21:00',
    location: 'The Comedy Cellar',
    image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?q=80&w=2070&auto=format&fit=crop',
    category: 'Comedy',
    capacity: 100,
    ticketsSold: 85,
    price: 30,
    organizer: 'Laugh Factory',
    organizerId: 'org7',
  },
  {
    id: '8',
    title: 'Indie Film Premiere: "The Void"',
    description: 'Be the first to see the award-winning independent film. Q&A with the director and cast after the screening.',
    date: '2026-05-05',
    time: '19:00',
    location: 'Angelika Film Center',
    image: 'https://images.unsplash.com/photo-1489599846354-00169d9d3d88?q=80&w=2070&auto=format&fit=crop',
    category: 'Movies',
    capacity: 300,
    ticketsSold: 120,
    price: 20,
    organizer: 'Indie Films',
    organizerId: 'org8',
  }
];
