spring.application.name=UserService

spring.datasource.url=jdbc:postgresql://ep-withered-recipe-aiuvdfem-pooler.c-4.us-east-1.aws.neon.tech/booking??sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2X5MAueiDrld
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=1111
